spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    testWhileIdle: true
    validationQuery: SELECT 1 from dual
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    # do not use this in production environment
    generate-ddl: true
    properties:
      hibernate:
        # do not use this in production environment
        hbm2ddl.auto: create-drop
        envers:
          autoRegisterListeners:
